[package]
org = "ballerina"
name = "math.vector"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["math", "vector", "distance"]
repository = "https://github.com/ballerina-platform/module-ballerina-math.vector"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.5.0"
