[package]
org = "ballerina"
name = "math.vector"
version = "1.1.1"
authors = ["Ballerina"]
keywords = ["math", "vector", "distance"]
repository = "https://github.com/ballerina-platform/module-ballerina-math.vector"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.12.0-20250226-081700-17d84e0f"
