[package]
org = "ballerina"
name = "math.vector"
version = "1.0.0"
authors = ["Ballerina"]
keywords = ["math", "vector", "distance"]
repository = "https://github.com/ballerina-platform/module-ballerina-math.vector"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.4"
